In [1]:
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SequentialFeatureSelector

df = pd.DataFrame({
    "Age":[22,25,47,52,46,56,48,55,60,61],
    "Salary":[25000,30000,80000,90000,70000,100000,85000,95000,110000,120000],
    "Experience":[1,2,10,15,9,18,11,17,20,21],
    "City":[0,1,0,1,0,1,0,1,0,1],
    "Purchased":[0,0,1,1,1,1,1,1,1,1]
})

X = df.drop(columns=["Purchased"])
y = df["Purchased"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression(max_iter=1000)

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=2,
    direction="backward"
)

selector.fit(X_train, y_train)

selected_features = X.columns[selector.get_support()]

print(selected_features)

X_new = X[selected_features]

print(X_new)

Index(['Experience', 'City'], dtype='object')
   Experience  City
0           1     0
1           2     1
2          10     0
3          15     1
4           9     0
5          18     1
6          11     0
7          17     1
8          20     0
9          21     1

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Experience":[1,2,5,7,10,12,15,18,20,22],
    "Salary":[25000,30000,45000,60000,70000,85000,95000,110000,120000,130000],
    "Education":[1,1,2,2,3,3,3,4,4,4],
    "Training_Hours":[5,8,20,25,30,35,40,45,50,55],
    "Performance":[60,65,75,80,85,88,90,94,96,98],
    "Promotion":[0,0,0,1,1,1,1,1,1,1]
})

x = df.drop(columns=["Promotion"])
y = df["Promotion"]


x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()


selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction="backward"
)

selector.fit(x_train,y_train)

selected_features = x.columns[selector.get_support()]

print(selected_features)

x_new = x[selected_features]

print(x_new)

Index(['Education', 'Training_Hours', 'Performance'], dtype='object')
   Education  Training_Hours  Performance
0          1               5           60
1          1               8           65
2          2              20           75
3          2              25           80
4          3              30           85
5          3              35           88
6          3              40           90
7          4              45           94
8          4              50           96
9          4              55           98

In [6]:
df = pd.DataFrame({
    "Age":[22,25,28,35,40,45,50,55,60,62],
    "Income":[20000,25000,30000,50000,70000,80000,90000,100000,110000,120000],
    "CreditScore":[550,580,620,700,750,770,790,810,830,850],
    "Dependents":[0,1,1,2,2,3,2,3,4,4],
    "LoanAmount":[100000,150000,180000,250000,300000,350000,400000,450000,500000,550000],
    "Approved":[0,0,0,1,1,1,1,1,1,1]
})

x = df.drop(columns=["Approved"])
y = df["Approved"]

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
    
)

model = LogisticRegression()

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction="backward"
)

selector.fit(x_train,y_train)

selected_features = x.columns[selector.get_support()]

print(selected_features)

x_new = x[selected_features]

x_new

Index(['Age', 'CreditScore', 'Dependents'], dtype='object')

   Age  CreditScore  Dependents
0   22          550           0
1   25          580           1
2   28          620           1
3   35          700           2
4   40          750           2
5   45          770           3
6   50          790           2
7   55          810           3
8   60          830           4
9   62          850           4

In [11]:
df = pd.DataFrame({
    "CGPA":[6.2,6.8,7.5,8.0,8.5,8.8,9.0,9.2,9.4,9.6],
    "Projects":[1,2,2,3,4,4,5,5,6,6],
    "Internship":[0,0,1,1,1,1,1,1,1,1],
    "Communication":[5,6,6,7,8,8,9,9,10,10],
    "Certifications":[0,1,1,2,2,3,3,4,4,5],
    "Placed":[0,0,0,1,1,1,1,1,1,1]
})

x = df.drop(columns=["Placed"])
y = df["Placed"]

x_train,x_test,y_train,y_trest = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction="backward"
)

selector.fit(x_train,y_train)

selected_features = x.columns[selector.get_support()]

print(selected_features)

x_new = x[selected_features]

x_new

Index(['Internship', 'Communication', 'Certifications'], dtype='object')

   Internship  Communication  Certifications
0           0              5               0
1           0              6               1
2           1              6               1
3           1              7               2
4           1              8               2
5           1              8               3
6           1              9               3
7           1              9               4
8           1             10               4
9           1             10               5

In [14]:
df = pd.DataFrame({
    "Age":[30,35,40,45,50,55,60,65,68,70],
    "BP":[120,125,130,140,145,150,155,160,165,170],
    "Cholesterol":[180,190,200,220,230,240,250,260,270,280],
    "Exercise":[6,5,5,4,3,2,2,1,1,0],
    "Weight":[60,65,68,72,75,80,82,85,88,90],
    "Disease":[0,0,0,1,1,1,1,1,1,1]
})


x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction="backward"
)

selector.fit(x_train,y_train)

selected_columns = x.columns[selector.get_support()]

print(selected_columns)

x_new = x[selected_columns]

x_new

Index(['Internship', 'Communication', 'Certifications'], dtype='object')

   Internship  Communication  Certifications
0           0              5               0
1           0              6               1
2           1              6               1
3           1              7               2
4           1              8               2
5           1              8               3
6           1              9               3
7           1              9               4
8           1             10               4
9           1             10               5

In [16]:
df = pd.DataFrame({
    "Age":[21,23,26,30,35,40,45,50,55,60],
    "Salary":[22000,25000,32000,50000,65000,80000,90000,100000,110000,120000],
    "FamilyMembers":[1,2,2,3,4,5,5,6,6,7],
    "Loan":[1,1,1,0,0,0,0,0,0,0],
    "DrivingExperience":[1,2,4,6,8,10,12,15,18,20],
    "Purchased":[0,0,0,1,1,1,1,1,1,1]
})

x = df.drop(columns=["Purchased"])
y = df["Purchased"]

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction="backward"
)

selector.fit(x_train,y_train)

selected_columns = x.columns[selector.get_support()]

print(selected_columns)

x_new = x[selected_columns]

x_new

Index(['Salary', 'Loan', 'DrivingExperience'], dtype='object')

   Salary  Loan  DrivingExperience
0   22000     1                  1
1   25000     1                  2
2   32000     1                  4
3   50000     0                  6
4   65000     0                  8
5   80000     0                 10
6   90000     0                 12
7  100000     0                 15
8  110000     0                 18
9  120000     0                 20