In [3]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")


from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import SequentialFeatureSelector

df = pd.DataFrame({
    "Age":[22,25,47,52,46,56,48,55,60,61],
    "Salary":[25000,30000,80000,90000,70000,100000,85000,95000,110000,120000],
    "Experience":[1,2,10,15,9,18,11,17,20,21],
    "City":[0,1,0,1,0,1,0,1,0,1],
    "Purchased":[0,0,1,1,1,1,1,1,1,1]
})

X = df.drop(columns=["Purchased"])
y = df["Purchased"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction="forward"
)

selector.fit(X_train, y_train)

selected_features = X.columns[selector.get_support()]

print(selected_features)

X_new = X[selected_features]

print(X_new)

Index(['Age', 'Salary', 'Experience'], dtype='object')
   Age  Salary  Experience
0   22   25000           1
1   25   30000           2
2   47   80000          10
3   52   90000          15
4   46   70000           9
5   56  100000          18
6   48   85000          11
7   55   95000          17
8   60  110000          20
9   61  120000          21

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Experience":[1,2,5,8,10,12,15,18,20,22],
    "Salary":[25000,30000,45000,60000,70000,85000,95000,110000,120000,130000],
    "Education":[1,1,2,2,3,3,3,4,4,4],
    "Training":[0,1,1,1,1,1,1,1,1,1],
    "Promotion":[0,0,0,1,1,1,1,1,1,1]
})

x = df.drop(columns=["Promotion"])
y = df["Promotion"]


x_train,x_test,y_train,y_test = train_test_split(
    x,y,
    test_size = 0.2,
    random_state=42
)

model = LogisticRegression()

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction = "forward"
)

selector.fit(x_train,y_train)

select_feature = x.columns[selector.get_support()]

print(select_feature)

x_new = x[select_feature]

x_new

Index(['Experience', 'Salary', 'Education'], dtype='object')

   Experience  Salary  Education
0           1   25000          1
1           2   30000          1
2           5   45000          2
3           8   60000          2
4          10   70000          3
5          12   85000          3
6          15   95000          3
7          18  110000          4
8          20  120000          4
9          22  130000          4

In [2]:
df = pd.DataFrame({
    "Age":[22,25,35,40,28,50,45,38,55,60],
    "Income":[20000,25000,50000,70000,30000,90000,80000,65000,100000,120000],
    "CreditScore":[550,580,700,750,620,800,780,720,820,850],
    "Dependents":[0,1,2,2,1,3,2,2,4,3],
    "LoanApproved":[0,0,1,1,0,1,1,1,1,1]
})

x = df.drop(columns=["LoanApproved"])
y = df["LoanApproved"]


model = LogisticRegression()

x_train,x_test,y_train,y_test = train_test_split(
    estimator=model,
    n_features_to_select = 3,
    direction="forward"
)

selector.fit(x_train,y_train)

select_feature = x.columns[selector.get_support()]

print(select_feature)

x_new = x[select_feature]

x_new

TypeError: got an unexpected keyword argument 'estimator'

In [4]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import SequentialFeatureSelector

df = pd.DataFrame({
    "Age":[22,25,35,40,28,50,45,38,55,60],
    "Income":[20000,25000,50000,70000,30000,90000,80000,65000,100000,120000],
    "CreditScore":[550,580,700,750,620,800,780,720,820,850],
    "Dependents":[0,1,2,2,1,3,2,2,4,3],
    "LoanApproved":[0,0,1,1,0,1,1,1,1,1]
})

x = df.drop(columns=["LoanApproved"])
y = df["LoanApproved"]

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction="forward"
)

selector.fit(x_train, y_train)

selected_features = x.columns[selector.get_support()]

print(selected_features)

x_new = x[selected_features]

print(x_new)

Index(['Age', 'Income', 'CreditScore'], dtype='object')
   Age  Income  CreditScore
0   22   20000          550
1   25   25000          580
2   35   50000          700
3   40   70000          750
4   28   30000          620
5   50   90000          800
6   45   80000          780
7   38   65000          720
8   55  100000          820
9   60  120000          850

In [6]:
df = pd.DataFrame({
    "Age":[22,25,35,40,28,50,45,38,55,60],
    "Income":[20000,25000,50000,70000,30000,90000,80000,65000,100000,120000],
    "CreditScore":[550,580,700,750,620,800,780,720,820,850],
    "Dependents":[0,1,2,2,1,3,2,2,4,3],
    "LoanApproved":[0,0,1,1,0,1,1,1,1,1]
})

x = df.drop(columns=["LoanApproved"])
y = df["LoanApproved"]

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction="forward"
)

selector.fit(x_train,y_train)

selected_features = x.columns[selector.get_support()]

print(selected_features)

x_new = x[selected_features]

x_new

Index(['Age', 'Income', 'CreditScore'], dtype='object')

   Age  Income  CreditScore
0   22   20000          550
1   25   25000          580
2   35   50000          700
3   40   70000          750
4   28   30000          620
5   50   90000          800
6   45   80000          780
7   38   65000          720
8   55  100000          820
9   60  120000          850

In [11]:
df = pd.DataFrame({
    "CGPA":[6.5,7.2,8.8,9.1,6.9,8.5,9.3,7.8,8.9,9.5],
    "Projects":[1,2,4,5,2,4,5,3,4,5],
    "Communication":[5,6,8,9,6,8,9,7,8,10],
    "Internship":[0,0,1,1,0,1,1,1,1,1],
    "Placed":[0,0,1,1,0,1,1,1,1,1]
})

x = df.drop(columns=["Placed"])
y = df["Placed"]

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()

selector = SequentialFeatureSelector(     
    estimator=model,
    n_features_to_select=3,
    direction="forward"
)

selector.fit(x_train,y_train)

selector_features = x.columns[selector.get_support()]


print(selector_features)

x_new = x[selector_features]

x_new

Index(['CGPA', 'Projects', 'Communication'], dtype='object')

   CGPA  Projects  Communication
0   6.5         1              5
1   7.2         2              6
2   8.8         4              8
3   9.1         5              9
4   6.9         2              6
5   8.5         4              8
6   9.3         5              9
7   7.8         3              7
8   8.9         4              8
9   9.5         5             10

In [16]:
df = pd.DataFrame({
    "Age":[30,35,45,50,55,60,40,48,52,65],
    "BP":[120,125,140,145,150,160,135,142,148,165],
    "Cholesterol":[180,190,220,230,240,260,210,225,235,270],
    "Exercise":[5,5,3,2,2,1,4,3,2,1],
    "Disease":[0,0,1,1,1,1,0,1,1,1]
})



x = df.drop(columns=["Disease"])
y = df["Disease"]

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction="forward"
)


selector.fit(x_train,y_train)

select_features = x.columns[selector.get_support()]

print(select_features)

x_new = x[select_features]

x_new

Index(['Age', 'BP', 'Cholesterol'], dtype='object')

   Age   BP  Cholesterol
0   30  120          180
1   35  125          190
2   45  140          220
3   50  145          230
4   55  150          240
5   60  160          260
6   40  135          210
7   48  142          225
8   52  148          235
9   65  165          270

In [21]:
df = pd.DataFrame({
    "Age":[21,24,30,35,28,40,45,50,55,60],
    "Salary":[20000,25000,45000,60000,35000,80000,90000,100000,110000,120000],
    "FamilyMembers":[1,2,3,4,2,5,5,6,6,7],
    "Loan":[1,1,0,0,1,0,0,0,0,0],
    "Purchased":[0,0,1,1,0,1,1,1,1,1]
})


x = df.drop(columns=["Purchased"])
y = df["Purchased"]

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression()

selector = SequentialFeatureSelector(
    estimator=model,
    n_features_to_select=3,
    direction="forward"
)

selector.fit(x_train,y_train)

select_features = x.columns[selector.get_support()]

print(select_features)

x_new = x[select_features]

print(x_new)

Index(['Age', 'FamilyMembers', 'Loan'], dtype='object')
   Age  FamilyMembers  Loan
0   21              1     1
1   24              2     1
2   30              3     0
3   35              4     0
4   28              2     1
5   40              5     0
6   45              5     0
7   50              6     0
8   55              6     0
9   60              7     0