In [1]:
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

In [2]:
import pandas as pd
import warnings

warnings.filterwarnings("ignore")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

df = pd.DataFrame({
    "Age":[22,25,30,35,40,45,50,55,60,65],
    "Salary":[25000,30000,45000,60000,70000,85000,95000,110000,120000,130000],
    "Experience":[1,2,4,6,8,10,12,15,18,20],
    "City":[0,1,0,1,0,1,0,1,0,1],
    "Purchased":[0,0,0,1,1,1,1,1,1,1]
})

X = df.drop(columns=["Purchased"])
y = df["Purchased"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression(max_iter=1000)

selector = RFE(
    estimator=model,
    n_features_to_select=2
)

selector.fit(X_train, y_train)

selected_features = X.columns[selector.get_support()]

print("Selected Features:")
print(selected_features)

X_new = X[selected_features]

print("\nNew Dataset:")
print(X_new)

Selected Features:
Index(['Salary', 'City'], dtype='object')

New Dataset:
   Salary  City
0   25000     0
1   30000     1
2   45000     0
3   60000     1
4   70000     0
5   85000     1
6   95000     0
7  110000     1
8  120000     0
9  130000     1

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Age":[22,25,28,30,35,40,45,50,55,60],
    "Experience":[1,2,4,5,8,10,12,15,18,20],
    "Education":[1,2,2,3,3,3,4,4,4,5],
    "Projects":[1,2,2,3,4,5,5,6,6,7],
    "Salary_High":[0,0,0,0,1,1,1,1,1,1]
})

x = df.drop(columns=["Salary_High"])
y = df["Salary_High"]

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression(max_iter=1000)

selector = RFE(
    estimator=model,
    n_features_to_select=2
)

selector.fit(x_train,y_train)

selected_columns = x.columns[selector.get_support()]

print(selected_columns)

x_new = x[selected_columns]

x_new

Index(['Age', 'Experience'], dtype='object')

   Age  Experience
0   22           1
1   25           2
2   28           4
3   30           5
4   35           8
5   40          10
6   45          12
7   50          15
8   55          18
9   60          20

In [5]:
df = pd.DataFrame({
    "CGPA":[6.2,6.8,7.0,7.5,8.0,8.5,8.8,9.0,9.3,9.5],
    "Internship":[0,0,0,1,1,1,1,1,1,1],
    "Communication":[5,6,6,7,8,8,9,9,10,10],
    "Projects":[1,2,2,3,4,4,5,5,6,6],
    "Placed":[0,0,0,1,1,1,1,1,1,1]
})

x = df.drop(columns=["Placed"])
y = df["Placed"]


x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression(max_iter=1000)

selector = RFE(
    estimator=model,
    n_features_to_select=3
)

selector.fit(x_train,y_train)

selected_columns = x.columns[selector.get_support()]

print(selected_columns)

x_new = x[selected_columns]

x_new

Index(['Internship', 'Communication', 'Projects'], dtype='object')

   Internship  Communication  Projects
0           0              5         1
1           0              6         2
2           0              6         2
3           1              7         3
4           1              8         4
5           1              8         4
6           1              9         5
7           1              9         5
8           1             10         6
9           1             10         6

In [7]:
df = pd.DataFrame({
    "Income":[20000,25000,30000,40000,50000,65000,80000,90000,100000,120000],
    "CreditScore":[550,580,610,650,700,740,770,800,830,850],
    "Age":[22,25,28,30,35,40,45,50,55,60],
    "Dependents":[0,1,1,2,2,3,2,3,4,4],
    "Approved":[0,0,0,0,1,1,1,1,1,1]
})


x = df.drop(columns=["Approved"])
y = df["Approved"]

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression(max_iter=20000)

selector = RFE(
    estimator=model,
    n_features_to_select=2
)

selector.fit(x_train,y_train)

selected_columns = x.columns[selector.get_support()]

print(selected_columns)

x_new = x[selected_columns]

x_new

Index(['CreditScore', 'Age'], dtype='object')

   CreditScore  Age
0          550   22
1          580   25
2          610   28
3          650   30
4          700   35
5          740   40
6          770   45
7          800   50
8          830   55
9          850   60

In [8]:
df = pd.DataFrame({
    "Age":[30,35,40,45,50,55,60,65,68,70],
    "BP":[120,125,130,140,145,150,155,160,165,170],
    "Exercise":[6,5,5,4,3,2,2,1,1,0],
    "Weight":[60,65,68,72,75,80,82,85,88,90],
    "Disease":[0,0,0,1,1,1,1,1,1,1]
})


x = df.drop(columns=["Disease"])
y = df["Disease"]

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=40
)

model = LogisticRegression(max_iter=1000)

selector = RFE(
    estimator=model,
    n_features_to_select=2
)

selector.fit(x_train,y_train)

selected_columns = x.columns[selector.get_support()]

print(selected_columns)

x_new = x[selected_columns]

x_new

Index(['Age', 'BP'], dtype='object')

   Age   BP
0   30  120
1   35  125
2   40  130
3   45  140
4   50  145
5   55  150
6   60  155
7   65  160
8   68  165
9   70  170

In [13]:
df = pd.DataFrame({
    "Age":[21,24,28,30,35,40,45,50,55,60],
    "Salary":[22000,26000,35000,50000,65000,80000,90000,100000,110000,120000],
    "Loan":[1,1,1,0,0,0,0,0,0,0],
    "DrivingExperience":[1,2,3,5,8,10,12,15,18,20],
    "FamilyMembers":[1,2,2,3,4,5,5,6,6,7],
    "Purchased":[0,0,0,1,1,1,1,1,1,1]
})



x = df.drop(columns=["Purchased"])
y = df["Purchased"]

x_train,x_test,y_train,y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=43
)

model = LogisticRegression(max_iter=1000)

selector = RFE(
    estimator=model,
    n_features_to_select=3
)

selector.fit(x_train,y_train)

selected_columns = x.columns[selector.get_support()]

print(selected_columns)

x_new = x[selected_columns]

x_new

Index(['Salary', 'Loan', 'DrivingExperience'], dtype='object')

   Salary  Loan  DrivingExperience
0   22000     1                  1
1   26000     1                  2
2   35000     1                  3
3   50000     0                  5
4   65000     0                  8
5   80000     0                 10
6   90000     0                 12
7  100000     0                 15
8  110000     0                 18
9  120000     0                 20