In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import VarianceThreshold

In [2]:
# Step 1 : Import Libraries

import pandas as pd
from sklearn.feature_selection import VarianceThreshold


# Step 2 : Create Dataset

df = pd.DataFrame({
    "Gender": [1, 1, 1, 1, 1],
    "Age": [18, 20, 22, 24, 26],
    "Salary": [30000, 35000, 40000, 45000, 50000]
})


# Step 3 : Separate Features (X)

X = df


# Step 4 : Create VarianceThreshold Object

selector = VarianceThreshold(threshold=0)


# Step 5 : Fit the Model

selector.fit(X)


# Step 6 : Check Selected Features (True = Keep, False = Remove)

print(selector.get_support())


# Step 7 : Display Selected Column Names

selected_columns = X.columns[selector.get_support()]
print(selected_columns)


# Step 8 : Create Final Dataset

final_dataset = X[selected_columns]

print(final_dataset)

[False  True  True]
Index(['Age', 'Salary'], dtype='object')
   Age  Salary
0   18   30000
1   20   35000
2   22   40000
3   24   45000
4   26   50000

In [6]:
import pandas as pd

df1 = pd.DataFrame({
    "Gender_Code": [1,1,1,1,1,1,1,1],
    "Area": [1000,1200,1400,1600,1800,2000,2200,2400],
    "Bedrooms": [2,2,3,3,4,4,5,5],
    "Parking": [1,2,1,2,2,3,3,4],
    "Age": [20,18,15,12,10,8,6,4],
    "Price": [45,55,68,80,95,110,125,145]
})
df1

   Gender_Code  Area  Bedrooms  Parking  Age  Price
0            1  1000         2        1   20     45
1            1  1200         2        2   18     55
2            1  1400         3        1   15     68
3            1  1600         3        2   12     80
4            1  1800         4        2   10     95
5            1  2000         4        3    8    110
6            1  2200         5        3    6    125
7            1  2400         5        4    4    145

In [12]:
x = df1

selector = VarianceThreshold(threshold=0)
selector.fit(x)

print(selector.get_support())
selected_columns = x.columns[selector.get_support()]
print(selected_columns)

final_dataset = x[selected_columns]

print(final_dataset)

[False  True  True  True  True  True]
Index(['Area', 'Bedrooms', 'Parking', 'Age', 'Price'], dtype='object')
   Area  Bedrooms  Parking  Age  Price
0  1000         2        1   20     45
1  1200         2        2   18     55
2  1400         3        1   15     68
3  1600         3        2   12     80
4  1800         4        2   10     95
5  2000         4        3    8    110
6  2200         5        3    6    125
7  2400         5        4    4    145

In [13]:
df2 = pd.DataFrame({
    "Country_Code": [101,101,101,101,101,101,101,101],
    "Engine": [800,1000,1200,1400,1600,1800,2000,2200],
    "Mileage": [25,23,21,19,18,17,16,15],
    "Weight": [700,800,900,1000,1100,1200,1300,1400],
    "Doors": [4,4,4,4,4,4,4,4],
    "Price": [5,6,7,9,11,13,16,18]
})
df2

   Country_Code  Engine  Mileage  Weight  Doors  Price
0           101     800       25     700      4      5
1           101    1000       23     800      4      6
2           101    1200       21     900      4      7
3           101    1400       19    1000      4      9
4           101    1600       18    1100      4     11
5           101    1800       17    1200      4     13
6           101    2000       16    1300      4     16
7           101    2200       15    1400      4     18

In [18]:
x = df2

selector = VarianceThreshold(threshold=0)
selector.fit(x)

print(selector.get_support())

selector_column = x.columns[selector.get_support()]
print(selector_column)

final_dataset = x[selector_column]

print(final_dataset)

[False  True  True  True False  True]
Index(['Engine', 'Mileage', 'Weight', 'Price'], dtype='object')
   Engine  Mileage  Weight  Price
0     800       25     700      5
1    1000       23     800      6
2    1200       21     900      7
3    1400       19    1000      9
4    1600       18    1100     11
5    1800       17    1200     13
6    2000       16    1300     16
7    2200       15    1400     18

In [1]:
# Step 1 : Import Library
from sklearn.feature_selection import VarianceThreshold

# Step 2 : Import Pandas
import pandas as pd

# Step 3 : Create Sample Dataset
df = pd.DataFrame({
    "Age": [20, 21, 22, 23, 24],
    "Salary": [30000, 32000, 31000, 33000, 34000],
    "Country": [1, 1, 1, 1, 1],
    "Gender": [0, 0, 0, 0, 1]
})

print("Original Dataset")
print(df)

# Step 4 : Create Variance Threshold Object
vt = VarianceThreshold(threshold=0.01)

# Step 5 : Fit and Transform the Dataset
X_new = vt.fit_transform(df)

# Step 6 : Get Selected Column Names
selected_columns = df.columns[vt.get_support()]

# Step 7 : Convert Back to DataFrame
new_df = pd.DataFrame(X_new, columns=selected_columns)

print("\nDataset After Variance Threshold")
print(new_df)

Original Dataset
   Age  Salary  Country  Gender
0   20   30000        1       0
1   21   32000        1       0
2   22   31000        1       0
3   23   33000        1       0
4   24   34000        1       1

Dataset After Variance Threshold
   Age  Salary  Gender
0   20   30000       0
1   21   32000       0
2   22   31000       0
3   23   33000       0
4   24   34000       1

In [2]:
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 21, 22, 23, 24],
    "Country": [1, 1, 1, 1, 1],
    "Salary": [30000, 32000, 31000, 33000, 34000]
})


selector = VarianceThreshold(threshold=0)
x_new = selector.fit_transform(df)

selected_column = df.columns[selector.get_support()]

new_df = pd.DataFrame(x_new,columns=selected_column)

print(new_df)

   Age  Salary
0   20   30000
1   21   32000
2   22   31000
3   23   33000
4   24   34000

In [12]:
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 21, 22, 23, 24],
    "Gender": [0, 0, 0, 0, 1],
    "Salary": [30000, 32000, 31000, 33000, 34000],
    "City": [1, 1, 1, 1, 1]
})

selector = VarianceThreshold(threshold=0.01)
x_new = selector.fit_transform(df)

selected_columns = df.columns[selector.get_support()]

new_df = pd.DataFrame(x_new,columns=selected_columns)

print(new_df)

   Age  Gender  Salary
0   20       0   30000
1   21       0   32000
2   22       0   31000
3   23       0   33000
4   24       1   34000

In [15]:
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 22, 25, 24, 26],
    "Salary": [30000, 32000, 35000, 33000, 36000],
    "Country": [1, 1, 1, 1, 1],
    "Purchased": [0, 1, 0, 1, 0]
})

se = VarianceThreshold(threshold=0)
x_new = se.fit_transform(df)

selected_columns = df.columns[se.get_support()]

new_df = pd.DataFrame(x_new,columns=selected_columns)

new_df

   Age  Salary  Purchased
0   20   30000          0
1   22   32000          1
2   25   35000          0
3   24   33000          1
4   26   36000          0

In [18]:
import pandas as pd

df = pd.DataFrame({
    "A": [1, 1, 1, 1, 1],
    "B": [5, 6, 7, 8, 9],
    "C": [10, 20, 30, 40, 50],
    "D": [0, 0, 0, 1, 0]
})

selector = VarianceThreshold(threshold=1)
x_new = selector.fit_transform(df)

selected_columns = df.columns[selector.get_support()]

df_new = pd.DataFrame(x_new,columns=selected_columns)

df_new

   B   C
0  5  10
1  6  20
2  7  30
3  8  40
4  9  50

In [27]:
import pandas as pd

df = pd.DataFrame({
    "Age": [20, 21, 22, 23, 24],
    "Salary": [30000, 31000, 32000, 33000, 34000],
    "Country": [1, 1, 1, 1, 1],
    "Gender": [0, 0, 0, 0, 1],
    "Purchased": [0, 1, 0, 1, 0]
})

se = VarianceThreshold(threshold=1)
x_new = se.fit_transform(df)

selected_columns = df.columns[se.get_support()]

df_new = pd.DataFrame(x_new,columns=selected_columns)
df_new

   Age  Salary
0   20   30000
1   21   31000
2   22   32000
3   23   33000
4   24   34000