In [3]:
import pandas as pd
from sklearn.feature_selection import mutual_info_classif

df = pd.DataFrame({
    "Age": [18, 20, 45, 50, 22, 48],
    "Salary": [25000, 30000, 80000, 90000, 28000, 85000],
    "Gender": [0, 1, 0, 1, 0, 1],
    "Purchased": [0, 0, 1, 1, 0, 1]
})

X = df.drop("Purchased", axis=1)
y = df["Purchased"]

mi_score = mutual_info_classif(X, y)

mi_score = pd.Series(mi_score, index=X.columns)

mi_score = mi_score.sort_values(ascending=False)

print(mi_score)

Age       0.700000
Salary    0.533333
Gender    0.000000
dtype: float64

In [2]:
mi_score = pd.DataFrame({
    "Features": X.columns,
    "MI Score": mi_score
})

In [10]:
import pandas as pd

df = pd.DataFrame({
    "Age": [18, 22, 25, 45, 50, 55],
    "Salary": [25000, 30000, 35000, 70000, 80000, 90000],
    "Gender": [0, 1, 0, 1, 0, 1],
    "Purchased": [0, 0, 0, 1, 1, 1]
})

x = df.drop("Purchased",axis=1)
y = df["Purchased"]

mi_score = mutual_info_classif(x,y)

mi_score = pd.DataFrame({
    "Features": x.columns,
    "MI Score": mi_score
})

mi_score = mi_score.sort_values(by="MI Score",ascending=True)

mi_score

  Features  MI Score
2   Gender  0.000000
0      Age  0.533333
1   Salary  0.616667

In [12]:
import pandas as pd

df = pd.DataFrame({
    "Study_Hours": [1, 2, 3, 6, 7, 8],
    "Attendance": [60, 65, 70, 90, 95, 98],
    "Sports": [1, 0, 1, 0, 1, 0],
    "Pass": [0, 0, 0, 1, 1, 1]
})


x = df.drop("Pass",axis=1)
y = df["Pass"]

mi_score = mutual_info_classif(x,y)

mi_score = pd.DataFrame({
    "Feature": x.columns,
    "Mi Score": mi_score
})

mi_score = mi_score.sort_values(by="Mi Score",ascending=True)

print(mi_score)

       Feature  Mi Score
2       Sports       0.0
0  Study_Hours       0.7
1   Attendance       0.7

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Experience": [1, 2, 3, 8, 10, 12],
    "Salary": [25000, 30000, 35000, 70000, 90000, 100000],
    "City_Code": [1, 2, 3, 2, 1, 3],
    "Education": [1, 1, 2, 3, 3, 2],
    "Promotion": [0, 0, 0, 1, 1, 1]
})

x = df.drop("Promotion",axis=1)
y = df["Promotion"]


mi_score = mutual_info_classif(x,y)

mi_score = pd.DataFrame({
    "Features":x.columns,
    "Mi Score":mi_score
})

mi_score = mi_score.sort_values(by="Features", ascending=False)

mi_score

     Features  Mi Score
1      Salary  0.533333
0  Experience  0.700000
3   Education  0.436111
2   City_Code  0.000000

In [4]:
import pandas as pd

df = pd.DataFrame({
    "Temperature": [30, 32, 35, 38, 40, 42],
    "Humidity": [80, 75, 70, 60, 55, 50],
    "Wind": [5, 6, 7, 8, 9, 10],
    "Rain": [1, 1, 0, 0, 0, 0]
})

x = df.drop("Rain",axis=1)
y = df["Rain"]

mi_scr = mutual_info_classif(x,y)
mi_scr = pd.DataFrame({
    "Feature": x.columns,
    "MI Score":mi_scr
})

mi_scr = mi_scr.sort_values(by="Feature",ascending=True)

mi_scr

       Feature  MI Score
1     Humidity  0.319444
0  Temperature  0.575000
2         Wind  0.519444

In [6]:
import pandas as pd

df = pd.DataFrame({
    "Age": [21, 23, 25, 35, 40, 45, 50, 55],
    "Income": [25000, 28000, 32000, 60000, 70000, 80000, 90000, 100000],
    "Credit_Score": [500, 550, 600, 700, 750, 800, 820, 850],
    "Experience": [0, 1, 2, 8, 10, 15, 18, 20],
    "City_Code": [1, 2, 1, 2, 3, 1, 3, 2],
    "Loan_Approved": [0, 0, 0, 1, 1, 1, 1, 1]
})

x = df.drop("Loan_Approved",axis=1)
y = df["Loan_Approved"]

mi_score = mutual_info_classif(x,y)
mi_score = pd.DataFrame({
    "Feature":x.columns,
    "MI Score":mi_score
})

mi_score = mi_score.sort_values(by="Feature",ascending=True)

mi_score

        Feature  MI Score
0           Age  0.526190
4     City_Code  0.000000
2  Credit_Score  0.457440
3    Experience  0.526190
1        Income  0.592857