In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame({
    "Gender": ["Male", "Female", "Male"],
    "Result": ["Pass", "Fail", "Pass"]
})

le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])

df["Result"] = le.fit_transform(df["Result"])

print(df)

   Gender  Result
0       1       1
1       0       0
2       1       1

In [2]:
df = pd.DataFrame({
    "Gender": ["Male", "Female", "Male", "Female", "Male"],
    "Age": [21, 20, 22, 19, 23]
})

le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])

print(df)

   Gender  Age
0       1   21
1       0   20
2       1   22
3       0   19
4       1   23

In [3]:
df = pd.DataFrame({
    "Result": ["Pass", "Fail", "Pass", "Pass", "Fail"],
    "Marks": [85, 32, 91, 76, 28]
})

le = LabelEncoder()

df["Result"] = le.fit_transform(df["Result"])

df

   Result  Marks
0       1     85
1       0     32
2       1     91
3       1     76
4       0     28

In [5]:
df = pd.DataFrame({
    "Department": ["HR", "IT", "Sales", "HR", "IT"],
    "Salary": [40000, 65000, 45000, 42000, 70000]
})

le = LabelEncoder()

df["Department"] = le.fit_transform(df["Department"])

print(df)

   Department  Salary
0           0   40000
1           1   65000
2           2   45000
3           0   42000
4           1   70000

In [6]:
df = pd.DataFrame({
    "Country": ["India", "USA", "Japan", "India", "USA"],
    "Purchase": [2500, 6000, 4500, 3000, 7000]
})

le = LabelEncoder()

df["Country"] = le.fit_transform(df["Country"])

print(df)

   Country  Purchase
0        0      2500
1        2      6000
2        1      4500
3        0      3000
4        2      7000

In [10]:
df = pd.DataFrame({
    "Blood_Group": ["A+", "O+", "B+", "AB+", "A+"],
    "Age": [25, 30, 22, 28, 24]
})

le = LabelEncoder()

df["Blood_Group"] = le.fit_transform(df["Blood_Group"])

print(df)

   Blood_Group  Age
0            0   25
1            3   30
2            2   22
3            1   28
4            0   24

In [11]:
df = pd.DataFrame({
    "Payment_Mode": ["Cash", "UPI", "Card", "Cash", "UPI"],
    "Amount": [1200, 850, 2500, 900, 1600]
})

le = LabelEncoder()

df["Payment_Mode"] = le.fit_transform(df["Payment_Mode"])

print(df)

   Payment_Mode  Amount
0             1    1200
1             2     850
2             0    2500
3             1     900
4             2    1600

In [13]:
df = pd.DataFrame({
    "Brand": ["Nike", "Puma", "Adidas", "Nike", "Puma"],
    "Price": [5000, 1200, 800, 3500, 1500]
})

le = LabelEncoder()

df["Brand"] = le.fit_transform(df["Brand"])

print(df)

   Brand  Price
0      1   5000
1      2   1200
2      0    800
3      1   3500
4      2   1500

In [14]:
df = pd.DataFrame({
    "Movie_Genre": ["Action", "Comedy", "Drama", "Comedy", "Action"],
    "Rating": [8.2, 7.5, 9.0, 7.8, 8.5]
})

le = LabelEncoder()

df["Movie_Genre"] = le.fit_transform(df["Movie_Genre"])

print(df)

   Movie_Genre  Rating
0            0     8.2
1            1     7.5
2            2     9.0
3            1     7.8
4            0     8.5

In [15]:
df = pd.DataFrame({
    "Disease": ["Fever", "Diabetes", "Cancer", "Fever", "Diabetes"],
    "Bill": [2000, 8000, 50000, 1800, 9000]
})

le = LabelEncoder()

df["Disease"] = le.fit_transform(df["Disease"])

print(df)

   Disease   Bill
0        2   2000
1        1   8000
2        0  50000
3        2   1800
4        1   9000

In [16]:
df = pd.DataFrame({
    "Course": ["BBA", "BCA", "MBA", "BCA", "BBA"],
    "Fees": [50000, 65000, 120000, 65000, 50000]
})

le = LabelEncoder()

df["Course"] = le.fit_transform(df["Course"])

df

   Course    Fees
0       0   50000
1       1   65000
2       2  120000
3       1   65000
4       0   50000

In [17]:
df = pd.DataFrame({
    "Gender": ["Male", "Female", "Male", "Female", "Male"],
    "Result": ["Pass", "Fail", "Pass", "Pass", "Fail"],
    "Marks": [85, 32, 91, 88, 40]
})

le = LabelEncoder()

df["Gender"] = le.fit_transform(df["Gender"])
df["Result"] = le.fit_transform(df["Result"])

print(df)

   Gender  Result  Marks
0       1       1     85
1       0       0     32
2       1       1     91
3       0       1     88
4       1       0     40

In [18]:
df = pd.DataFrame({
    "Country": ["India", "USA", "Japan", "India", "USA"],
    "Department": ["HR", "IT", "Sales", "HR", "IT"],
    "Payment": ["Cash", "UPI", "Card", "Cash", "UPI"],
    "Salary": [40000, 65000, 45000, 42000, 70000]
})

le = LabelEncoder()

df["Country"] = le.fit_transform(df["Country"])
df["Department"] = le.fit_transform(df["Department"])
df["Payment"] = le.fit_transform(df["Payment"])

print(df)

   Country  Department  Payment  Salary
0        0           0        1   40000
1        2           1        2   65000
2        1           2        0   45000
3        0           0        1   42000
4        2           1        2   70000

In [21]:
df = pd.DataFrame({
    "Gender": ["Male", "Female", "Male", "Female"],
    "Department": ["HR", "IT", "Sales", "HR"],
    "Result": ["Pass", "Fail", "Pass", "Pass"],
    "Country": ["India", "USA", "Japan", "India"],
    "Age": [21, 22, 20, 23],
    "Salary": [40000, 60000, 50000, 45000]
})

le = LabelEncoder()

columns = ["Gender","Department","Result","Country"]

for col in columns:
    df[col] = le.fit_transform(df[col])

print(df)

   Gender  Department  Result  Country  Age  Salary
0       1           0       1        0   21   40000
1       0           1       0        2   22   60000
2       1           2       1        1   20   50000
3       0           0       1        0   23   45000