In [5]:
import pandas as pd

df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Blue", "Red"]
})


df = pd.get_dummies(df,dtype=float)

df

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0

In [4]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({
    "City": ["Pune", "Mumbai", "Delhi", "Pune"]
})

encoder = OneHotEncoder()

encoded = encoder.fit_transform(df[["City"]])

encoded_df = pd.DataFrame(
    encoded.toarray(),
    columns=encoder.get_feature_names_out()
)

print(encoded_df)

   City_Delhi  City_Mumbai  City_Pune
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0

In [6]:
df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Blue", "Red"]
})

df = pd.get_dummies(df,dtype=float)
df

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0

In [7]:
df

   Color_Blue  Color_Green  Color_Red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0

In [15]:
df = pd.DataFrame({
    "City": ["Pune", "Mumbai", "Delhi", "Pune", "Mumbai"]
})

encoder = OneHotEncoder() 

encoded = encoder.fit_transform(df[["City"]])

encoded_df = pd.DataFrame(
    encoded.toarray(),
    columns = encoder.get_feature_names_out()
)

print(encoded_df)

   City_Delhi  City_Mumbai  City_Pune
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0
4         0.0          1.0        0.0

In [16]:
df = pd.DataFrame({
    "Department": ["HR", "IT", "Sales", "IT", "HR"]
})

df = pd.get_dummies(df,dtype=int)

df

   Department_HR  Department_IT  Department_Sales
0              1              0                 0
1              0              1                 0
2              0              0                 1
3              0              1                 0
4              1              0                 0

In [19]:
df = pd.DataFrame({
    "Gender": ["Male", "Female", "Male", "Female"],
    "City": ["Pune", "Mumbai", "Delhi", "Pune"]
})


df = pd.get_dummies(df, columns = ["City"],dtype=float)
df

   Gender  City_Delhi  City_Mumbai  City_Pune
0    Male         0.0          0.0        1.0
1  Female         0.0          1.0        0.0
2    Male         1.0          0.0        0.0
3  Female         0.0          0.0        1.0

In [20]:
df = pd.DataFrame({
    "Country": ["India", "USA", "Japan", "India"],
    "Payment": ["Cash", "UPI", "Card", "Cash"]
})

df = pd.get_dummies(df,dtype=float)

print(df)

   Country_India  Country_Japan  Country_USA  Payment_Card  Payment_Cash  \
0            1.0            0.0          0.0           0.0           1.0
1            0.0            0.0          1.0           0.0           0.0
2            0.0            1.0          0.0           1.0           0.0
3            1.0            0.0          0.0           0.0           1.0

   Payment_UPI
0          0.0
1          1.0
2          0.0
3          0.0

In [22]:
df = pd.DataFrame({
    "Brand": ["Nike", "Puma", "Adidas", "Nike"],
    "Price": [5000, 3000, 4000, 6000]
})

encoder = OneHotEncoder()

encoded = encoder.fit_transform(df[["Brand"]])

encoded_df = pd.DataFrame(
    encoded.toarray(),
    columns = encoder.get_feature_names_out()

)

print(encoded_df)

   Brand_Adidas  Brand_Nike  Brand_Puma
0           0.0         1.0         0.0
1           0.0         0.0         1.0
2           1.0         0.0         0.0
3           0.0         1.0         0.0

In [23]:
df = pd.DataFrame({
    "Food": ["Pizza", "Burger", "Pizza", "Sandwich"],
    "Drink": ["Tea", "Coffee", "Juice", "Tea"]
})

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df)

encoded_df = pd.DataFrame(
    encoded,
    columns = encoder.get_feature_names_out()
)

print(encoded_df)

   Food_Burger  Food_Pizza  Food_Sandwich  Drink_Coffee  Drink_Juice  \
0          0.0         1.0            0.0           0.0          0.0
1          1.0         0.0            0.0           1.0          0.0
2          0.0         1.0            0.0           0.0          1.0
3          0.0         0.0            1.0           0.0          0.0

   Drink_Tea
0        1.0
1        0.0
2        0.0
3        1.0

In [25]:
df = pd.DataFrame({
    "City": ["Pune", "Mumbai", "Delhi", "Pune"],
    "Age": [21, 22, 20, 23],
    "Salary": [40000, 50000, 45000, 60000]
})

encoded = OneHotEncoder()

encoder = encoded.fit_transform(df[["City"]])

encoded_df = pd.DataFrame(
    encoder.toarray(),
    columns = encoded.get_feature_names_out()
)

print(encoded_df)

   City_Delhi  City_Mumbai  City_Pune
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0

In [28]:
df = pd.DataFrame({
    "Gender": ["Male", "Female", "Male", "Female"],
    "Department": ["HR", "IT", "Sales", "HR"],
    "City": ["Pune", "Mumbai", "Delhi", "Pune"]
})

encoder = OneHotEncoder()

encoded = encoder.fit_transform(df)

encoded_df = pd.DataFrame(
    encoded.toarray(),
    columns = encoder.get_feature_names_out()
)

print(encoded_df)

   Gender_Female  Gender_Male  Department_HR  Department_IT  Department_Sales  \
0            0.0          1.0            1.0            0.0               0.0
1            1.0          0.0            0.0            1.0               0.0
2            0.0          1.0            0.0            0.0               1.0
3            1.0          0.0            1.0            0.0               0.0

   City_Delhi  City_Mumbai  City_Pune
0         0.0          0.0        1.0
1         0.0          1.0        0.0
2         1.0          0.0        0.0
3         0.0          0.0        1.0

In [32]:
df = pd.DataFrame({
    "Gender": ["Male", "Female", "Male", "Female"],
    "Department": ["HR", "IT", "Sales", "HR"],
    "City": ["Pune", "Mumbai", "Delhi", "Pune"],
    "Age": [21, 22, 20, 23],
    "Salary": [40000, 50000, 45000, 60000]
})

columns = ["Gender","Department","City"]
col1 = ["Age","Salary"]

encoded = OneHotEncoder()

encoder = encoded.fit_transform(df[columns])

encoded_df = pd.DataFrame(
    encoder.toarray(),
    columns = encoded.get_feature_names_out()
)

final_data = pd.concat([df[col1],encoded_df],axis=1)

print(final_data)

   Age  Salary  Gender_Female  Gender_Male  Department_HR  Department_IT  \
0   21   40000            0.0          1.0            1.0            0.0
1   22   50000            1.0          0.0            0.0            1.0
2   20   45000            0.0          1.0            0.0            0.0
3   23   60000            1.0          0.0            1.0            0.0

   Department_Sales  City_Delhi  City_Mumbai  City_Pune
0               0.0         0.0          0.0        1.0
1               0.0         0.0          1.0        0.0
2               1.0         1.0          0.0        0.0
3               0.0         0.0          0.0        1.0

In [35]:
df = pd.DataFrame({
    "Color": ["Red", "Blue", "Green", "Blue"],
    "Brand": ["Nike", "Puma", "Nike", "Adidas"],
    "City": ["Pune", "Mumbai", "Delhi", "Pune"],
    "Price": [5000, 3000, 4500, 6000],
    "Rating": [4.5, 4.2, 4.8, 4.1]
})

columns = ["Color","Brand","City"]
col1 = ["Price","Rating"]

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[columns])

encoded_df = pd.DataFrame(
    encoded,
    columns = encoder.get_feature_names_out()
)

DataSet = pd.concat([df[col1],encoded_df],axis=1)
print(DataSet)

   Price  Rating  Color_Blue  Color_Green  Color_Red  Brand_Adidas  \
0   5000     4.5         0.0          0.0        1.0           0.0
1   3000     4.2         1.0          0.0        0.0           0.0
2   4500     4.8         0.0          1.0        0.0           0.0
3   6000     4.1         1.0          0.0        0.0           1.0

   Brand_Nike  Brand_Puma  City_Delhi  City_Mumbai  City_Pune
0         1.0         0.0         0.0          0.0        1.0
1         0.0         1.0         0.0          1.0        0.0
2         1.0         0.0         1.0          0.0        0.0
3         0.0         0.0         0.0          0.0        1.0