In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

df = pd.DataFrame({
    "Size": ["M", "L", "S", "XL", "M"]
})

encoder = OrdinalEncoder(
    categories=[["S", "M", "L", "XL"]]
)

df["Size"] = encoder.fit_transform(df[["Size"]])

print(df)

   Size
0   1.0
1   2.0
2   0.0
3   3.0
4   1.0

In [3]:
df = pd.DataFrame({
    "Performance": ["Poor", "Average", "Good", "Excellent", "Good"]
})

encoder = OrdinalEncoder(
    categories=[["Poor","Average","Good","Excellent"]]
)

df["Performance"] = encoder.fit_transform(df[["Performance"]])

print(df)

   Performance
0          0.0
1          1.0
2          2.0
3          3.0
4          2.0

In [4]:
df = pd.DataFrame({
    "Size": ["M", "L", "S", "XL", "M"]
})

encoder = OrdinalEncoder(
    categories = [["S","M","L","XL"]]
)

df["Size"] = encoder.fit_transform(df[["Size"]])

print(df)

   Size
0   1.0
1   2.0
2   0.0
3   3.0
4   1.0

In [6]:
df = pd.DataFrame({
    "Education": [
        "College",
        "School",
        "PhD",
        "Master",
        "College"
    ]
})

encoder = OrdinalEncoder(
    categories = [["School","College","Master","PhD"]]
)

df["Education"] = encoder.fit_transform(df[["Education"]])

print(df)

   Education
0        1.0
1        0.0
2        3.0
3        2.0
4        1.0

In [7]:
df = pd.DataFrame({
    "Rating": [
        "Good",
        "Excellent",
        "Bad",
        "Average",
        "Good"
    ]
})

encoder = OrdinalEncoder(
    categories = [["Bad","Average","Good","Excellent"]]
)

df["Rating"] = encoder.fit_transform(df[["Rating"]])

print(df)

   Rating
0     2.0
1     3.0
2     0.0
3     1.0
4     2.0

In [8]:
df = pd.DataFrame({
    "Temperature": [
        "Warm",
        "Cold",
        "Hot",
        "Warm",
        "Cold"
    ]
})

encoder = OrdinalEncoder(
    categories = [["Cold","Warm","Hot"]]
)

df["Temperature"] = encoder.fit_transform(df[["Temperature"]])

df

   Temperature
0          1.0
1          0.0
2          2.0
3          1.0
4          0.0

In [9]:
df = pd.DataFrame({
    "Priority": [
        "High",
        "Low",
        "Medium",
        "High",
        "Low"
    ]
})

encoder = OrdinalEncoder(
    categories = [["Low","Medium","High"]]
)


df[["Priority"]] = encoder.fit_transform(df[["Priority"]])

print(df)

   Priority
0       2.0
1       0.0
2       1.0
3       2.0
4       0.0

In [11]:
df = pd.DataFrame({
    "Size": ["S", "M", "L", "XL"],
    "Performance": [
        "Poor",
        "Good",
        "Average",
        "Excellent"
    ]
})

encoder = OrdinalEncoder(
    categories = [
        ["S","M","L","XL"],
        ["Poor","Average","Good","Excellent"]
    ]
)

df[["Size","Performance"]] = encoder.fit_transform(df[["Size","Performance"]])

print(df)

   Size  Performance
0   0.0          0.0
1   1.0          2.0
2   2.0          1.0
3   3.0          3.0

In [13]:
df = pd.DataFrame({
    "Education": [
        "College",
        "School",
        "Master",
        "PhD"
    ],
    "Priority": [
        "Medium",
        "High",
        "Low",
        "Medium"
    ]
})

encoder = OrdinalEncoder(
    categories = [
        ["School","College","Master","PhD"],
        ["Low","Medium","High"]
    ]
)

df[["Education","Priority"]] = encoder.fit_transform(df[["Education","Priority"]])

df

   Education  Priority
0        1.0       1.0
1        0.0       2.0
2        2.0       0.0
3        3.0       1.0

In [18]:
df = pd.DataFrame({
    "Experience": [
        "Intermediate",
        "Beginner",
        "Expert",
        "Intermediate"
    ],
    "Salary": [
        40000,
        30000,
        80000,
        50000
    ]
})

encoder = OrdinalEncoder(
    categories = [["Beginner","Intermediate","Expert"]]
)

df[["Experience"]] = encoder.fit_transform(df[["Experience"]])

print(df)

   Experience  Salary
0         1.0   40000
1         0.0   30000
2         2.0   80000
3         1.0   50000

In [20]:
df = pd.DataFrame({
    "Education": [
        "School",
        "College",
        "Master",
        "PhD"
    ],
    "Size": [
        "M",
        "XL",
        "S",
        "L"
    ],
    "Performance": [
        "Good",
        "Poor",
        "Excellent",
        "Average"
    ],
    "Age": [
        20,
        22,
        25,
        24
    ]
})

encoder = OrdinalEncoder(
    categories = [
        ["School","College","Master","PhD"],
        ["S","M","L","XL"],
        ["Poor","Average","Good","Excellent"]
    ]
)

df[["Education","Size","Performance"]] = encoder.fit_transform(df[["Education","Size","Performance"]])

print(df)

   Education  Size  Performance  Age
0        0.0   1.0          2.0   20
1        1.0   3.0          0.0   22
2        2.0   0.0          3.0   25
3        3.0   2.0          1.0   24

In [21]:
df = pd.DataFrame({
    "Risk": [
        "High",
        "Medium",
        "Low",
        "Medium",
        "High"
    ],
    "Customer": [
        "Gold",
        "Silver",
        "Bronze",
        "Gold",
        "Silver"
    ],
    "Loan": [
        500000,
        200000,
        100000,
        300000,
        450000
    ]
})

encoder = OrdinalEncoder(
    categories = [
        ["Low","Medium","High"],
        ["Bronze","Silver","Gold"]
    ]
)


df[["Risk","Customer"]] = encoder.fit_transform(df[["Risk","Customer"]])

   Risk  Customer    Loan
0   2.0       2.0  500000
1   1.0       1.0  200000
2   0.0       0.0  100000
3   1.0       2.0  300000
4   2.0       1.0  450000