In [1]:
from sklearn.feature_selection import chi2
import pandas as pd

df = pd.DataFrame({
    "Gender": [1, 0, 1, 0, 1, 0],
    "Education": [2, 1, 2, 1, 2, 1],
    "City": [1, 2, 1, 2, 1, 2],
    "Purchased": [1, 0, 1, 0, 1, 0]
})
X = df.drop("Purchased", axis=1)
y = df["Purchased"]

chi_score, p_value = chi2(X, y)
chi_df = pd.DataFrame({
    "Feature": X.columns,
    "Chi Score": chi_score,
    "P Value": p_value
})

chi_df = chi_df.sort_values(
    by="Chi Score",
    ascending=False
)

chi_df

     Feature  Chi Score   P Value
0     Gender        3.0  0.083265
1  Education        1.0  0.317311
2       City        1.0  0.317311

In [ ]:
import pandas as pd

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

df = pd.read_csv("loan.csv")

X = df.drop(columns=["Loan"])
y = df["Loan"]

selector = SelectKBest(score_func=chi2, k=3)

X_new = selector.fit_transform(X, y)

score = pd.DataFrame({
    "Feature": X.columns,
    "Score": selector.scores_
})

print(score)

In [9]:
import pandas as pd
from sklearn.feature_selection import chi2
from sklearn.feature_selection import SelectKBest

df = pd.DataFrame({
    "Gender": [1,0,1,0,1,0,1,1,0,0],
    "Study_Hours": [2,5,6,1,8,3,7,4,2,9],
    "Attendance": [60,90,85,55,95,70,92,80,65,98],
    "Sports": [1,0,0,1,0,1,0,1,1,0],
    "Admission": [0,1,1,0,1,0,1,1,0,1]
})

x = df.drop(columns=["Admission"])
y = df["Admission"]

selector = SelectKBest(score_func=chi2,k=2)

x_new = selector.fit_transform(x,y)

new_df = pd.DataFrame({
    "Feature":x.columns,
    "Score":selector.scores_
})

new_df

       Feature      Score
0       Gender   0.833333
1  Study_Hours  10.340426
2   Attendance  22.974684
3       Sports   3.333333

In [11]:
df = pd.DataFrame({
    "Gender":[1,0,1,1,0,1,0,1,0,1],
    "Married":[1,1,0,1,0,1,0,1,0,1],
    "Education":[1,0,1,1,0,1,0,1,1,0],
    "Credit_History":[1,0,1,1,0,1,0,1,0,1],
    "Loan_Approved":[1,0,1,1,0,1,0,1,0,1]
})

x = df.drop(columns=["Loan_Approved"])
y = df["Loan_Approved"]

selector = SelectKBest(score_func=chi2,k=3)

x_new = selector.fit_transform(x,y)

new_df2 = pd.DataFrame({
    "Features":x.columns,
    "Score":selector.scores_
})

new_df2

         Features     Score
0          Gender  4.000000
1         Married  1.361111
2       Education  1.361111
3  Credit_History  4.000000

In [12]:
df = pd.DataFrame({
    "Age_Group":[1,2,3,2,1,3,2,1,3,2],
    "Income_Level":[1,2,3,2,1,3,3,2,1,2],
    "Student":[1,0,0,1,1,0,0,1,1,0],
    "Credit_Rating":[1,1,0,0,1,0,1,0,1,0],
    "Buy_Mobile":[0,1,1,1,0,1,1,0,0,1]
})

x = df.drop(columns=["Buy_Mobile"])
y = df["Buy_Mobile"]

selector = SelectKBest(score_func=chi2,k=3)
x_new = selector.fit_transform(x,y)

new_df = pd.DataFrame({
    "Features":x.columns,
    "Score":selector.scores_
})

new_df

        Features     Score
0      Age_Group  0.833333
1   Income_Level  1.875000
2        Student  3.333333
3  Credit_Rating  0.833333

In [13]:
df = pd.DataFrame({
    "Fever":[1,0,1,1,0,1,0,1,1,0],
    "Cough":[1,1,1,0,0,1,0,1,0,0],
    "Body_Pain":[1,0,1,0,0,1,0,1,1,0],
    "Headache":[1,0,1,1,0,1,0,0,1,0],
    "Disease":[1,0,1,1,0,1,0,1,1,0]
})

x = df.drop(columns=["Disease"])
y = df["Disease"]

selector = SelectKBest(score_func=chi2,k=2)

x_new = selector.fit_transform(x,y)

df_new = pd.DataFrame({
    "Feature":x.columns,
    "Score":selector.scores_
})

df_new

     Feature     Score
0      Fever  4.000000
1      Cough  0.833333
2  Body_Pain  3.333333
3   Headache  3.333333

In [17]:
df = pd.DataFrame({
    "Gender":[1,0,1,0,1,0,1,1,0,1],
    "Salary":[25,60,70,30,90,40,100,75,35,95],
    "Married":[1,0,1,0,1,0,1,1,0,1],
    "Own_House":[0,1,1,0,1,0,1,1,0,1],
    "Purchased":[0,1,1,0,1,0,1,1,0,1]
})

x = df.drop(columns=["Purchased"])
y = df["Purchased"]

selector = SelectKBest(score_func=chi2,k=3)

x_new = selector.fit_transform(x,y)

new_df1 = pd.DataFrame({
    "Feature":x.columns,
    "Score":selector.scores_
})

new_df1

     Feature      Score
0     Gender   1.361111
1     Salary  93.575269
2    Married   1.361111
3  Own_House   4.000000

In [19]:
df = pd.DataFrame({
    "Experience":[1,2,5,8,3,6,7,2,9,4],
    "Education":[1,2,2,3,1,3,2,1,3,2],
    "Training":[0,1,1,1,0,1,1,0,1,1],
    "Department":[1,2,1,3,2,3,1,2,3,1],
    "Promotion":[0,0,1,1,0,1,1,0,1,1]
})
x = df.drop(columns=["Promotion"])
y = df["Promotion"]

selector = SelectKBest(score_func=chi2,k=3)
x_new = selector.fit_transform(x,y)

n_df = pd.DataFrame({
    "Feature":x.columns,
    "Score":selector.scores_
})

n_df

      Feature      Score
0  Experience  10.340426
1   Education   1.875000
2    Training   1.928571
3  Department   0.078947

In [21]:
df = pd.DataFrame({
    "Gender":[1,0,1,1,0,1,0,1,0,1],
    "Visited":[2,8,9,6,3,10,2,9,4,8],
    "Clicked_Ads":[1,1,1,0,0,1,0,1,0,1],
    "Member":[0,1,1,0,0,1,0,1,0,1],
    "Purchased":[0,1,1,0,0,1,0,1,0,1]
})

x = df.drop(columns=["Purchased"])
y = df["Purchased"]

selector = SelectKBest(score_func=chi2,k=2)
x_new = selector.fit_transform(x,y)

b_df = pd.DataFrame({
    "Feature":x.columns,
    "Score":selector.scores_
})

b_df

       Feature      Score
0       Gender   0.666667
1      Visited  11.950820
2  Clicked_Ads   2.666667
3       Member   5.000000

In [25]:
df = pd.DataFrame({
    "Age_Group":[1,2,3,2,1,3,2,1,3,2],
    "Balance":[20,50,80,60,25,90,55,30,95,70],
    "Loan":[1,0,1,1,0,1,0,0,1,1],
    "Credit_Card":[0,1,1,0,1,1,0,1,1,0],
    "Exited":[0,1,1,0,0,1,0,0,1,1]
})

x = df.drop(columns=["Exited"])
y = df["Exited"]


selector = SelectKBest(score_func=chi2,k=3)
x_new = selector.fit_transform(x,y)

d_df = pd.DataFrame({
    "Feature":x.columns,
    "Score":selector.scores_
})

d_df

       Feature      Score
0    Age_Group   1.800000
1      Balance  66.130435
2         Loan   0.666667
3  Credit_Card   0.666667

In [27]:
df = pd.DataFrame({
    "Gender":[1,0,1,0,1,0,1,1,0,1],
    "OverTime":[1,0,1,0,1,0,1,1,0,1],
    "Job_Level":[1,2,3,2,1,3,2,1,3,2],
    "Travel":[2,1,3,1,2,3,2,1,3,2],
    "Attrition":[1,0,1,0,1,0,1,1,0,1]
})

x = df.drop(columns=["Attrition"])
y = df["Attrition"]

selector = SelectKBest(score_func=chi2,k=3)
x_new = selector.fit_transform(x,y)

pd_df = pd.DataFrame({
    "Feature":x.columns,
    "Score":selector.scores_
})

pd_df

     Feature     Score
0     Gender  4.000000
1   OverTime  4.000000
2  Job_Level  0.833333
3     Travel  0.000000

In [28]:
df = pd.DataFrame({
    "CGPA":[6,8,9,7,5,9,8,6,7,9],
    "Internship":[0,1,1,0,0,1,1,0,1,1],
    "Communication":[5,8,9,6,5,9,8,6,7,9],
    "Projects":[1,3,4,2,1,5,4,2,3,5],
    "Placed":[0,1,1,0,0,1,1,0,1,1]
})
x = df.drop(columns=["Placed"])
y = df["Placed"]

selector = SelectKBest(score_func=chi2,k=3)
x_new = selector.fit_transform(x,y)

df_f = pd.DataFrame({
    "Feature":x.columns,
    "Score":selector.scores_
})

df_f

         Feature     Score
0           CGPA  1.765766
1     Internship  4.000000
2  Communication  2.675926
3       Projects  5.000000